### ISSUE TITLE
Create initial setup for DoMoreSpices Backend

### ISSUE THREAD

**Issue by domorespices** [domorespices/Domorespices#1]
[GOAL]
To create initial springboot setup for domorespices backend

a)Create and test for startup locally
b)Push the code to github repo

Name of package: TBD

**Comment by kasirajr** [comment]
Spring boot requires intellij enterprise version, what to do

**Comment by domorespices** [comment]
Not necessarily. You can do with community also.

**Comment by domorespices** [comment]
Couple of things

It is possible to create using community version. There are a couple of
hacks

If you feel it's not worth the effort go for eclipse

**Comment by kasirajr** [comment]
Done with the initial setup, where to push the code
